apiVersion: v1
kind: Service
metadata:
  name: db-postgresql-block-explorer
spec:
  selector:
    service: db-postgresql-block-explorer
  ports:
    - protocol: TCP
      targetPort: 5432
      port: 5432
      name: tcp
  type: LoadBalancer
